APP:
    NAME: gin.weibo
    RUNMODE: debug # 模式： debug ,release, test
    Addr: :8888
    URL: http://local.ginweibo.com
    KEY: base64:O+VQ74YEigLPDzLKnh2HW/yjCdU2ON9v7xuKBgSOEAo=
    ENABLE_CSRF: true # 是否开启 csrf

DB:
    CONNECTION: mysql
    HOST: 127.0.0.1
    PORT: 3306
    DATABASE: gin_weibo
    USERNAME: root
    PASSWORD: root
